# Generated by Django 5.0.4 on 2024-04-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_has_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expected_2fa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
