# Generated by Django 5.0.4 on 2024-04-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_expected_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
