# Generated by Django 5.0.4 on 2024-04-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_expiration_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
