# Generated by Django 5.0.4 on 2024-04-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_email_code_user_email_code_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_code_expiration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expected_2fa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expiration_2fa',
        ),
    ]
