# Generated by Django 5.0.4 on 2024-10-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player1', models.CharField()),
                ('player2', models.CharField()),
                ('player3', models.CharField()),
                ('player4', models.CharField()),
                ('semi_winner_1', models.CharField()),
                ('semi_winner_2', models.CharField()),
                ('final_winner', models.CharField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
