version: '3.3'

services:
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: .
    networks:
      - internal
    ports:
      - "443:443"
    depends_on:
      - postgres
      - redis-service
    env_file:
      - .env

  redis-service:
    container_name: redis-service
    image: redis:6.2-alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - internal

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    env_file:
      - .env


networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
    driver_opts:
      type: none
      device: ~/data/database
      o: bind
  redis_data:
    driver_opts:
      type: none
      device: ~/data/redis
      o: bind
