version: '3.3'

services:
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: Backend
    environment:
      # This is to ignore the local .env file in the backend,
      # so that the environment variables are read from the .env file in the root directory
      IGNORE_DOTENV: 'true'
    volumes:
      - ./Backend/Api:/app
    networks:
      - internal
    depends_on:
      - postgres
    env_file:
      - .env


  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: Frontend
      args:
        - DOMAIN=${DOMAIN}
        - DJANGO_ADMIN_DOMAIN=${DJANGO_ADMIN_DOMAIN}
    volumes:
      - ./Frontend:/var/www/frontend
    ports:
      - "443:443"
    networks:
      - internal
    depends_on:
      - backend
    env_file:
      - .env

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    env_file:
      - .env


networks:
  internal:
    driver: bridge

volumes:
    postgres_data:
      driver_opts:
        type: none
        device: ./data/database
        o: bind