# Generated by Django 5.0.4 on 2024-04-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
